spring:
  datasource:
    url: jdbc:h2:file:./TestDataBase/test
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect


